import { Outfit } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const outfit = Outfit({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Test Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased overflow-x-hidden`}>
        <Suspense>{children}</Suspense>
      </body>
    </html>
  );
}
